# Generated by Django 5.2 on 2025-10-30 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('ticker_symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('industry', models.CharField(max_length=100)),
                ('offering_date', models.DateField()),
                ('offering_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shares_offered', models.IntegerField()),
                ('total_proceeds', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fraud_risk_score', models.IntegerField(default=0)),
                ('risk_category', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='LOW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FraudAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('risk_factors', models.JSONField()),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recommendations', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_analyses', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='RedFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('REVENUE_GROWTH_ANOMALY', 'Revenue Growth Anomaly'), ('PROFITABILITY_ISSUES', 'Profitability Issues'), ('HIGH_LEVERAGE', 'High Leverage'), ('LARGE_OFFERING_SIZE', 'Large Offering Size'), ('RELATED_PARTY_TRANSACTIONS', 'Related Party Transactions'), ('AUDITOR_ISSUES', 'Auditor Issues'), ('MANAGEMENT_TURNOVER', 'Management Turnover'), ('INCONSISTENT_FINANCIALS', 'Inconsistent Financials')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_flags', to='companies.company')),
            ],
        ),
    ]
